version: '3.8'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: todo
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - todo-network
  app:
    depends_on:
      - db
    image: todo-app
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - todo-network
networks:
  todo-network:
    driver: bridge